//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SQLite;

namespace App_news_Androind.Model
{
    
    public partial class LoaiTin
    {
        [PrimaryKey, NotNull]
        public long Id { get; set; }
        public string DisplayName { get; set; }
    
    }
}
