//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_news_Androind.Model
{
    
    public partial class TinTuc
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Content { get; set; }
        public string imgn { get; set; }
        public long IdUser { get; set; }
        public int IdLoaiTin { get; set; }
        public string NgayDang { get; set; }
        public string LinkCT { get; set; }
    }
}
