//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_news_desktop.Model
{
    using App_news_desktop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinTuc()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
        }

        private long _Id { get; set; }
        public long Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private string _DisplayName { get; set; }
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private string _Content { get; set; }
        public string Content { get => _Content; set { _Content = value; OnPropertyChanged(); } }
        private string _imgn { get; set; }
        public string imgn { get => _imgn; set { _imgn = value; OnPropertyChanged(); } }
        private long _IdUser { get; set; }
        public long IdUser { get => _IdUser; set { _IdUser = value; OnPropertyChanged(); } }
        private long _IdLoaiTin { get; set; }
        public long IdLoaiTin { get => _IdLoaiTin; set { _IdLoaiTin = value; OnPropertyChanged(); } }
        private string _NgayDang { get; set; }
        public string NgayDang { get => _NgayDang; set { _NgayDang = value; OnPropertyChanged(); } }
        private string _LinkCT { get; set; }
        public string LinkCT { get => _LinkCT; set { _LinkCT = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual LoaiTin LoaiTin { get; set; }
        public virtual Users Users { get; set; }
    }
}
