//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_news_desktop.Model
{
    using App_news_desktop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Users:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.TinTuc = new HashSet<TinTuc>();
        }

        private long _Id { get; set; }
        public long Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private string _DisplayName { get; set; }
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private string _UserName { get; set; }
        public string UserName { get => _UserName; set { _UserName = value; OnPropertyChanged(); } }
        private string _Password { get; set; }
        public string Password { get => _Password; set { _Password = value; OnPropertyChanged(); } }
        private long _IdQuyen { get; set; }
        public long IdQuyen { get => _IdQuyen; set { _IdQuyen = value; OnPropertyChanged(); } }
        private string _ViTri { get; set; }
        public string ViTri { get => _ViTri; set { _ViTri = value; OnPropertyChanged(); } }
        private string _imgn { get; set; }
        public string imgn { get => _imgn; set { _imgn = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual Quyen Quyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuc> TinTuc { get; set; }
    }
}
